---
title: "Check data"
author: "AL"
date: "21/09/2020"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
editor_options:
  chunk_output_type: console
up-dated: 03/10/2020
---

# Summary  

Explore ranges of QUAL and DP

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r echo=F}
options(width = 999)
```

# Start section

```{r}

Sys.time()
gc()
options(stringsAsFactors=F)

```

# Read data

```{r}

scripts_folder="/rds/project/erf33/rds-erf33-medgen/users/mae/RMS_2020Sept/RMS_cclgAB/scripts/s02_vqsr"
setwd(scripts_folder)

data_folder="/rds/project/erf33/rds-erf33-medgen/users/mae/RMS_2020Sept/RMS_cclgAB/data/s02_vqsr"
data.df <- read.table(file.path(data_folder,"CCLG_GL_hg38.bwa_10bp_vqsr_filt_annotations.txt"), 
                          header=T, quote="", sep="\t", comment.char = "")

colnames(data.df) <- c("CHROM","POS","ID","REF","ALT","FILTER","QUAL","DP","VQSLOD")

dim(data.df)
head(data.df)

```

# Check QUAL and DP

```{r}

quantile(data.df$QUAL)
quantile(data.df$DP)

hist(data.df$QUAL)
hist(log10(data.df$QUAL))

hist(data.df$DP)
hist(log10(data.df$DP))

```

# End section

```{r}

ls()
Sys.time()
gc()
sessionInfo()

```
